<?php

namespace App\Http\Requests;

use App\Rules\CategoryParent;

class CategoryCatalogRequest extends CatalogRequest
{
    /**
     * @var string[]
     */
    protected $entity = [
        'name' => 'category',
        'table' => 'categories'
    ];

    /**
     * @return bool
     */
    public function authorize()
    {
        return parent::authorize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|\string[][]
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \string[][]
     */
    protected function createItem()
    {
        $rules = [
            'parent_id' => [
                'required',
                'regex:~^[0-9]+$~',
            ],
        ];

        return array_merge(parent::createItem(), $rules);
    }

    /**
     * @return array[]|\string[][]
     */
    protected function updateItem()
    {
        $model = $this->route('category');
        $rules = [
            'parent_id' => [
                'required',
                'regex:~^[0-9]+$~',
                new CategoryParent($model)
            ],
        ];

        return array_merge(parent::updateItem(), $rules);
    }
}
